#- Carsten's PDK. Borders, symbols, loop stability
cpdk:
  remote: git@github.com:wulffern/cpdk.git
  revision: main

#- Technology library
tech_ihp13g2:
  remote: git@github.com:wulffern/tech_ihp13g2.git
  revision: main

lelo_tr_ihp13g2:
  remote: git@github.com:wulffern/lelo_tr_ihp13g2.git
  revision: main

lelo_atr_ihp13g2:
  remote: git@github.com:wulffern/lelo_atr_ihp13g2.git
  revision: main
